### ISSUE TITLE
Web of science authors have no prefLabel

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#197] opened 2018-10-17 21:23 UTC
```sparql
SELECT ?p ?q WHERE {
    <http://sul.stanford.edu/rialto/agents/people/acba55e9-1073-4fe2-b994-6bba0e504aac> ?p ?q.
}
```

```json
{
  "head" : {
    "vars" : [ "p", "q" ]
  },
  "results" : {
    "bindings" : [ {
      "p" : {
        "type" : "uri",
        "value" : "http://vivoweb.org/ontology/core#relatedBy"
      },
      "q" : {
        "type" : "uri",
        "value" : "http://sul.stanford.edu/rialto/context/positions/http://sul.stanford.edu/rialto/agents/organizations/a0e3977c-2021-4e31-a87a-0cb357363310_acba55e9-1073-4fe2-b994-6bba0e504aac"
      }
    }, {
      "p" : {
        "type" : "uri",
        "value" : "http://www.w3.org/2006/vcard/ns#hasAddress"
      },
      "q" : {
        "type" : "uri",
        "value" : "http://sul.stanford.edu/rialto/context/addresses/acba55e9-1073-4fe2-b994-6bba0e504aac_WOS:000380911100007"
      }
    } ]
  }
}
```

**Comment by justinlittman** [comment] 2018-10-18 11:09
I strongly suspect that this is bad data in Neptune. Locally loaded data has a prefLabel.

![screen shot 2018-10-18 at 6 56 18 am](https://user-images.githubusercontent.com/588335/47150517-ce280980-d2a4-11e8-98de-49feb8c1d205.png)

**Comment by mjgiarlo** [comment] 2018-10-18 16:51
I've been working on the malformed position URI, caused by bad data in RIALTO Core (a bunch of orgs with `/agents/organizations/` instead of `/agents/orgs/`). All of the offending orgs are now deleted, so I will now work on reloading the 1.2K or so Stanford orgs from the Profiles API.

@justinlittman Should I delete all the WoS authors and let the work in https://github.com/sul-dlss/rialto/issues/271 repopulate the orgs and authors that I delete?

**Comment by mjgiarlo** [comment] 2018-10-18 17:55
All data in Neptune has been wiped. Once we have a documented way to wipe the derivative datastores, I will begin reloading data in Neptune so we can see it derived in the web application.

**Comment by mjgiarlo** [comment] 2018-10-18 17:58
I don't believe there's any more work required for this issue, other than a full re-load. I will do that as part of https://github.com/sul-dlss/rialto/issues/271. I will add two acceptance criteria to that issue:

* Ensure position URIs are not malformed
* Ensure WoS authors have `prefLabel`s

Closing.

**Closed by mjgiarlo** 2018-10-18 17:58 UTC
Labels: in progress
